language: java

jdk:
  - oraclejdk8

after_success:
  - ls -l $TRAVIS_BUILD_DIR
  - java -jar $TRAVIS_BUILD_DIR/config/lib/codacy-coverage-reporter-4.0.2-assembly.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml


before_install:
  - chmod +x gradlew
